"""empty message

Revision ID: c19a2972f943
Revises: 5fd78fb0f679
Create Date: 2023-09-09 07:30:59.258525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19a2972f943'
down_revision = '5fd78fb0f679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_element_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'elements', ['characters'], ['id'])
        batch_op.create_foreign_key(None, 'elements', ['planets'], ['id'])
        batch_op.drop_column('element_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_element_id_fkey', 'elements', ['element_id'], ['id'])
        batch_op.drop_column('planets')
        batch_op.drop_column('characters')

    # ### end Alembic commands ###
