"""empty message

Revision ID: ebd1044bc588
Revises: c19a2972f943
Create Date: 2023-09-09 08:46:42.510882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd1044bc588'
down_revision = 'c19a2972f943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_planets_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_characters_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['characters'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planets'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_characters_fkey', 'elements', ['characters'], ['id'])
        batch_op.create_foreign_key('favorites_planets_fkey', 'elements', ['planets'], ['id'])

    # ### end Alembic commands ###
